export const SET_EXTERNAL_API_LISTENER = 'SET_EXTERNAL_API_LISTENER';
export const REMOVE_EXTERNAL_API_LISTENER = 'REMOVE_EXTERNAL_API_LISTENER';
export const ADD_CALLKIT_URL = 'ADD_CALLKIT_URL';
export const ADD_CALLKIT_NAME = "ADD_CALLKIT_NAME";
export const ADD_CALLKIT_UUID = "ADD_CALLKIT_UUID";
